micronaut:
  application:
    name: micronautSample
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/compare_native_images
    driverClassName: org.mariadb.jdbc.Driver
    username: cardoso
    password: 112358
    schema-generate: NONE
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages: 'br.com.cardoso.micronaut.entity'